---
title: "Beta Regression"
output: html_notebook
---

```{r}
data <- read.csv('datathon.csv', header = TRUE)
```

# beta reg
## zero-inflated beta regression model

```{r}
#install.packages("gamlss")
library(gamlss)
set.seed(6666)

beta_Thailand <- gamlss(Thailand ~ Thailand2 + Thailand3 + Thailand4 + time, 
                        mu.link = logit, family = BEZI, data = data, trace = F)
summary(beta_Thailand)
```

Set up coefficient estimate and sd
```{r}
df = data.frame('country' = c('Australia', 'Canada', 'China',
                              'Germany','Netherlands', 'Thailand', 'United.Kingdom',
                              'Austria', 'Belgium', 'India', 'Kazakhstan',
                               'Turkey','United Arab Emirates'), 
                'beta1' = NaN, 'beta2' = NaN, 'beta3' = NaN, 'beta4' = NaN,
                'beta1_sd' = NaN, 'beta2_sd' = NaN, 'beta3_sd' = NaN, 
                'beta4_sd' = NaN)
df[df$country == 'Turkey', 'beta1'] = -3.72619 
df[df$country == 'Turkey', 'beta2'] = -0.01053
df[df$country == 'Turkey', 'beta4'] = -0.00832
df[df$country == 'Turkey', 'beta1_sd'] = 1.06949
df[df$country == 'Turkey', 'beta2_sd'] = 0.06179
df[df$country == 'Turkey', 'beta4_sd'] = 0.11312 

df[df$country == 'India', 'beta1'] = -3.404098
df[df$country == 'India', 'beta2'] = 0.003958
df[df$country == 'India', 'beta4'] = -0.015511
df[df$country == 'India', 'beta1_sd'] = 1.746484
df[df$country == 'India', 'beta2_sd'] = 0.025517
df[df$country == 'India', 'beta4_sd'] = 0.071803

df[df$country == 'Belgium', 'beta1'] = -4.416474
df[df$country == 'Belgium', 'beta2'] = -0.000224
df[df$country == 'Belgium', 'beta3'] = -0.011368
df[df$country == 'Belgium', 'beta1_sd'] = 0.643996
df[df$country == 'Belgium', 'beta3_sd'] = 0.008713
df[df$country == 'Belgium', 'beta4_sd'] = 1.049721

df[df$country == 'Thailand', 'beta1'] = -4.2640334
df[df$country == 'Thailand', 'beta2'] = -0.0431903
df[df$country == 'Thailand', 'beta4'] = 0.3390842
df[df$country == 'Thailand', 'beta1_sd'] = 0.5604216
df[df$country == 'Thailand', 'beta2_sd'] = 0.0439729
df[df$country == 'Thailand', 'beta4_sd'] = 0.6404710

df[df$country == 'Germany', 'beta1'] = -4.386624
df[df$country == 'Germany', 'beta2'] = -0.001261
df[df$country == 'Germany', 'beta4'] = -0.028985 
df[df$country == 'Germany', 'beta1_sd'] = 3.561829
df[df$country == 'Germany', 'beta2_sd'] = 0.012398
df[df$country == 'Germany', 'beta4_sd'] = 0.602646

df[df$country == 'China', 'beta1'] = -4.911458
df[df$country == 'China', 'beta2'] = -0.001599
df[df$country == 'China', 'beta4'] = -0.070885 
df[df$country == 'China', 'beta1_sd'] = 0.438563
df[df$country == 'China', 'beta2_sd'] = 0.032863
df[df$country == 'China', 'beta4_sd'] = 0.055471

df[df$country == 'Canada', 'beta1'] = -15.11434
df[df$country == 'Canada', 'beta2'] = -0.08059
df[df$country == 'Canada', 'beta4'] = 0.67048
df[df$country == 'Canada', 'beta1_sd'] = 6.29151
df[df$country == 'Canada', 'beta2_sd'] = 0.02437
df[df$country == 'Canada', 'beta4_sd'] = 0.50638

df[df$country == 'Australia', 'beta1'] = -2.446566
df[df$country == 'Australia', 'beta2'] = -0.008614
df[df$country == 'Australia', 'beta4'] = -0.367331 
df[df$country == 'Australia', 'beta1_sd'] = 0.773931
df[df$country == 'Australia', 'beta2_sd'] = 0.008177
df[df$country == 'Australia', 'beta4_sd'] = 0.072787

df
```


```{r}
df_odds_ratio = data.frame('country' = countries, beta1_ci_lower = NaN,
                           beta1_ci_higher = NaN, beta2_ci_lower = NaN,
                           beta2_ci_higher = NaN, beta3_ci_lower = NaN,
                           beta3_ci_higher = NaN, beta4_ci_lower = NaN,
                           beta4_ci_higher = NaN)
for (i in 1:4){
  for (j in 1:length(countries)){
    beta_ci_low <- df[j, i+1] - 1.96*df[j, i+5]
    beta_ci_high <- df[j, i+1] + 1.96*df[j, i+5]
    df_odds_ratio[j, i*2] = exp(beta_ci_low)
    df_odds_ratio[j, i*2+1] = exp(beta_ci_high)
  }
}
df_odds_ratio
```

## forest plot
```{r}
library(ggplot2)
```

```{r}
df4 <- data.frame('idx' = 1:7, 'center' = 0, 'sd' = 0)
df4['center'] = (df_odds_ratio$beta4_ci_lower + df_odds_ratio$beta4_ci_higher)/2
df4['sd'] = (df_odds_ratio$beta4_ci_higher - df_odds_ratio$beta4_ci_lower)/2
df4 <- na.omit(df4)
df4$idx = 1:6
df4
```

```{r}
ggplot(df4, aes(x=idx, y=center)) + 
  geom_pointrange(aes(ymin=center-sd, ymax=center+sd)) + theme_light() +
  geom_hline(yintercept = 1, color = 'red', lty = 2) +
  xlab("country") + ylab("beta2")
```

```{r}
df3 <- data.frame('idx' = 1:7, 'center' = 0, 'sd' = 0)
df3['center'] = (df_odds_ratio$beta3_ci_lower + df_odds_ratio$beta3_ci_higher)/2
df3['sd'] = (df_odds_ratio$beta3_ci_higher - df_odds_ratio$beta3_ci_lower)/2
df3 <- na.omit(df3)
df3
```

```{r}
ggplot(df3, aes(x=idx, y=center)) + 
  geom_pointrange(aes(ymin=center-sd, ymax=center+sd)) + theme_light() +
  geom_hline(yintercept = 1, color = 'red', lty = 2) +
  xlab("country") + ylab("beta2")
```

```{r}
df2 <- data.frame('idx' = 1:7, 'center' = 0, 'sd' = 0)
df2['center'] = (df_odds_ratio$beta2_ci_lower + df_odds_ratio$beta2_ci_higher)/2
df2['sd'] = (df_odds_ratio$beta2_ci_higher - df_odds_ratio$beta2_ci_lower)/2
df2 <- na.omit(df2)
df2
```

```{r}
ggplot(df2, aes(x=idx, y=center)) + 
  geom_pointrange(aes(ymin=center-sd, ymax=center+sd)) + theme_light() +
  geom_hline(yintercept = 1, color = 'red', lty = 2) +
  xlab("country") + ylab("beta2")
```





